#!/bin/bash
avail=/etc/httpd/sites-enabled/$1.conf
enabled=/etc/httpd/sites-enabled
site=`ls /etc/httpd/sites-enabled/`

if [ "$#" != "1" ]; then
    echo "Use script: a2dissite virtual_site"
    echo -e "\nVirtual hosts yang tersedia: \n$site"
    exit 0
else

    if test -e $avail; then
        sudo rm  $avail
    else
        echo -e "$avail virtual host tak ditemukan! Silahkan buat terlebih dulu!"
        exit 0
    fi

    if test -e $enabled/$1.conf; then
        echo "Error!! Tidak dapat menghapus virtual host $avail !"
    else
        echo  -e "Sukses! $avail telah dihapus!\nSilahkan restart Apache: sudo systemctl 
restart httpd"
        exit 0
    fi
fi
